apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gstools-cert
  namespace: default
spec:
  commonName: gst.freeyeti.net
  secretName: gstools-issuer-key
  dnsNames:
    - gst.freeyeti.net
  issuerRef:
    name: gstools-issuer
    kind: ClusterIssuer